version: '3.3'

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
    #- ./nginx-config/:/etc/nginx/
    - ./nginx-conf-d/:/etc/nginx/conf.d/
    ports:
      - 80:80
    restart: always
